### ISSUE TITLE
Epic: Discontinue, migrate or document legacy hosts

### ISSUE THREAD

**Issue by hellais** [ooni/devops#120]
We did a inventory of all of our current infrastructure to plan this area of work.

Highest priority is discontinuing things on eclipsis so that we are able to fall within the new 50 credits/month tier.

## Greenhost (ghs)

* [x] ams-wcth2.ooni.nu (37.218.245.117) -> machine killed
* [x] ams-wcth3.ooni.nu (37.218.247.47) -> machine killed
* [ ] db-1.proteus.ooni.io (37.218.242.79) 56.80 -> we should make a backup of the DB, migrate ams-ps to ooni-backend and discontinue. Alternatively move it over to our prod postgresql database.
* [ ] ams-matomo.ooni.nu (37.218.242.173) 34.10 -> we should make a backup of the DB and kill the machine
* [ ] ams-ps.ooni.nu (37.218.245.90) 31.30 -> we should either switch to using ooni-backend for this or keep it but switch to use prod postgres DB.
* [ ] mia-echoth.ooni.nu (37.218.241.93) 7.40 -> keep or migrate, yet migration requires writing code to support this legacy codebase
* [ ] mia-httpth.ooni.nu (37.218.241.94) 7.40 -> keep or migrate, yet migration requires writing code to support this legacy codebase
* [ ] ams-slack-1.ooni.org (37.218.247.98) 7.40 -> keep or migrate
* [x] api-test-geoip (37.218.244.46) 54.10 -> machine killed
* [x] greenhost-beacon.ooni.org (37.218.243.110) 7.40 -> machine killed
* [x] explorer-redirector.ooni.nu (37.218.242.29) 24.50 -> machine killed
* [ ] openvpn-server1.prod.ooni.io 14.80 -> keep or migrate

## Hetzner (htz)

* [x] monitoring.ooni.org 38 -> playbook migration complete. Should eventually migrate jupyter over to notebook.ooni.org. TODO figure out how to monitor nodes in AWS.
* [ ] backend-fsn.ooni.org 116 -> Should be moved to EC2
* [ ] backend-hel.ooni.org 130 -> Should be moved to EC2
* [x] data1.htz-fsn.prod.ooni.nu 122 -> New clickhouse cluster node. Hot primary replicated host. Setup complete.
* [ ] data2.htz-fsn.prod.ooni.nu 129 -> New clickhouse cluster node. Hot secondary replicated host. Keep, but needs to be re-initialized
* [x] notebook.ooni.org 36 -> New jupyter notebook server. Setup complete.
* [x] data3.htz-fsn.prod.ooni.nu -> New clickhouse cluster. Cold backup replicated store with slow drives. Setup complete.

### AWS

* Consolidate microservices into bigger ones
* Work to be done related to moving terraform provisioning over from ansible configs
* Move secrets manager to parameter store
* Look into task memory allocations and consider dropping them

### Digital Ocean

* [ ] wcth-prod[0-2]
* [ ] wcth-dev
* [ ] countly -> running a very out of date version
