### ISSUE TITLE
Migrate/Discontinue greenhost machines

### ISSUE THREAD

**Issue by hellais** [ooni/devops#121]
We should do the following in order to fit within the 50 credits/month tier:

## To do by January 2025

* [x] db-1.proteus.ooni.io (37.218.242.79) 56.80 -> see: https://github.com/ooni/devops/issues/128
* [x] ams-matomo.ooni.nu (37.218.242.173) 34.10 -> see: https://github.com/ooni/devops/issues/129
* [x] openvpn-server1.prod.ooni.io 14.80 -> Migrate over to digital ocean, https://github.com/ooni/devops/issues/195

## To do after
* [x] ams-ps.ooni.nu (37.218.245.90) 31.30 -> we should either switch to using ooni-backend for this or keep it but switch to use prod postgres DB. This is needed for returning test targets to probes. https://github.com/ooni/devops/issues/196
* ~[ ] mia-echoth.ooni.nu (37.218.241.93) 7.40 -> keep or migrate, yet migration requires writing code to support this legacy codebase~
* ~[ ] mia-httpth.ooni.nu (37.218.241.94) 7.40 -> keep or migrate, yet migration requires writing code to support this legacy codebase~
* ~[ ] ams-slack-1.ooni.org (37.218.247.98) 7.40 -> keep or migrate~

**Comment by hellais** [comment]
Once we tackle the slack-in host, we should consider adding support for better monitoring, since we had run into issues with it returning networking errors. Also we should probably upgrade it to a later version of the software.

**Comment by hellais** [comment]
I am closing this epic since all the high priority hosts have been either migrated or discontinued.

The follow up issues for this are: https://github.com/ooni/devops/issues/224 & https://github.com/ooni/devops/issues/197
